// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCULacfJQCGckIX29ts04r35e0DqGk_ZSc',
    appId: '1:91891815469:web:f1d8587c72f643de0e14a4',
    messagingSenderId: '91891815469',
    projectId: 'medically-5c839',
    authDomain: 'medically-5c839.firebaseapp.com',
    storageBucket: 'medically-5c839.appspot.com',
    measurementId: 'G-EYQZKB3ZEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQL2ggzfg5NEmPVj1GivqH4WZopf2IhpA',
    appId: '1:91891815469:android:3b56a172786777320e14a4',
    messagingSenderId: '91891815469',
    projectId: 'medically-5c839',
    storageBucket: 'medically-5c839.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASrCDLL5-KyAdmWphQUl9KfT3xDwmpaAY',
    appId: '1:91891815469:ios:817990e42575a76b0e14a4',
    messagingSenderId: '91891815469',
    projectId: 'medically-5c839',
    storageBucket: 'medically-5c839.appspot.com',
    androidClientId: '91891815469-3scbpd84p6ivd1qmoe8kjinibd5oo2mq.apps.googleusercontent.com',
    iosClientId: '91891815469-tq1h3mpfbvju023ovofrf9jaqqsmgp2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicAlly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASrCDLL5-KyAdmWphQUl9KfT3xDwmpaAY',
    appId: '1:91891815469:ios:817990e42575a76b0e14a4',
    messagingSenderId: '91891815469',
    projectId: 'medically-5c839',
    storageBucket: 'medically-5c839.appspot.com',
    androidClientId: '91891815469-3scbpd84p6ivd1qmoe8kjinibd5oo2mq.apps.googleusercontent.com',
    iosClientId: '91891815469-tq1h3mpfbvju023ovofrf9jaqqsmgp2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicAlly',
  );
}
